name: Web Page Interaction with Puppeteer

on:
  push:
    branches:
      - testing

jobs:
  interact_with_webpage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: cd testing && npm install

      - name: Run Puppeteer test
        run: cd testing && npm test

      - name: Run Puppeteer script
        run: |
          node testing/checkSmartscriptOnExamples.js
